include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/prisma_client.dart

linter:
  rules:
    - always_use_package_imports
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
    - unawaited_futures
