name: sql_server_data_source
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dotenv: ^4.1.0
  json_annotation: ^4.8.0
  orm: ^3.1.2
  uuid: ^3.0.6

  api_data_source:
    path: ../api_data_source

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.16.0
