name: api_data_source
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  data_class_plugin: 0.2.0
  uuid: ^3.0.6

dev_dependencies:
  test: ^1.19.2
  lints: ^2.0.1
